name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v1
    - name: Dependencies install
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Format Check
      run: npm run format-check
    - name: Tests
      run: npm test
    - name: build
      run: npm run build
